on: push
name: Run phpunit testsuite
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: jackmdavis97/php:7.3

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Change to the correct directory
      run: |
        cd examples/laravel-framework
    - name: Install composer dependencies
      run: |
        composer install
    - name: Prepare Laravel Application
      run: |
        cp .env.example .env
        php artisan key:generate
    - name: Run Testsuite
      run: vendor/bin/phpunit tests/